version: 0.2

# Environment variables for the build
env:
  variables:
    AWS_DEFAULT_REGION: "eu-west-2"
    AWS_ACCOUNT_ID: "494376414941"
    IMAGE_REPO_NAME: "devops-day3-app"
    IMAGE_TAG: "latest"

phases:
  # Pre-build phase: Login to ECR and pull dependencies
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - echo $AWS_DEFAULT_REGION
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo Building Docker image with tag $IMAGE_TAG

  # Build phase: Build the Docker image
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - cd app
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
      - echo Build completed on `date`

  # Post-build phase: Push image to ECR and create deployment artifact
  post_build:
    commands:
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"devops-day3-app","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json

# Artifacts that will be passed to the deploy stage
artifacts:
  files:
    - imagedefinitions.json
    - app/**/*

# Cache Docker layers for faster builds
cache:
  paths:
    - '/root/.docker/**/*'
